### ISSUE TITLE
Implement questions report system

### ISSUE THREAD

**Issue by JeronimoMendes** [HackerSchool/Arquimedia#240]
Users need a way to report questions that have some sort of error. 
- [x] Create `Report` model
- [x] Create CRD endpoints

**Comment by afonsofsdomingues** [comment]
I was thinking about creating a `Report` model with the following fields:

- **Question**, to be able to link the anomaly to the report (foreign key)
- **Name**, to be able to link the person to the report (foreign key)
- **Date**, so that we can have an organised log of the issues by date, which allows us to prioritize issues and track what issues have already been solved
- **Type of issue**, dropdown list with info about the issue (mistake, problem with the submission, other,...)
- **Body**, description of the issue

**Comment by JeronimoMendes** [comment]
> * **Name**, to be able to link the person to the report (foreign key)

Looks good to me.
I suggest naming it `author` as it is a more descriptive field name.
